### PR TITLE
129 page transition

### LINKED ISSUE #129: Feature : Page Transition
Add a transition whenever you switch between pages

### PR DESCRIPTION
**Pull request by OussamaMasri**
whenever you press on the page you want to go to a small transition will be activated

### CODE REVIEW

**Review by Iseluin — APPROVED** [review]
Loved it !

**Review by sarahaboudalal — APPROVED** [review]
COOLLL

**Review by ayubabdullah — APPROVED** [review]
Great work

**Review by MARWAHAKMI — APPROVED** [review]
Good Work Oussama 👌
But for code to be cleaned, you can create inside the animation folder a component for page transition and reuse it in all pages without duplication in code.

**Review by OmarBassatni97 — APPROVED** [review]

**Pull request merged**
