### PR TITLE
35 feature sign in and sign up with user credentials

### LINKED ISSUE #35: Feature : Sign In and Sign Up with User Credentials
## Summary

Users must be able to sign in to the website through Firebase Authentication by creating an account with their username and with the password of their choice. 

Users should have a record created in the firestore database, for example in a users collection so we can save their credentials they have.

Also, when that happens, the user should also be saved in a slice (usersSlice maybe?).

### Screenshots

N/A

### Basic example

N/A

### Motivation
We need to be able to authenticate users to be able to implement user specific functionality.

### PR DESCRIPTION
**Pull request by OussamaMasri**

### CODE REVIEW

**Comment by OmarBassatni97** [comment]
Oussama do we need to store the users in a store?

**Comment by OussamaMasri** [comment]
> Oussama do we need to store the users in a store?

As I understood from Kutay we have to store all of the Users first name and last name inside of the FireStore

**Review by ayubabdullah — DISMISSED** [review]
Good work oussama

but add handling the error that comes back from the firebase, like duplicate emails or server errors and so on,

after the successful sign up redirect the user to the home

**Review by Iseluin — APPROVED** [review]
👍🏻

**Pull request merged**
