### PR TITLE
18 create contact us page

### LINKED ISSUE #18: Create : Contact Us Page
## Summary

Users should be able to e-mail us with their problems and desires. Create a controlled form with validation schemas added. Sending e-mail functionality will be added later.

Design and responsiveness must be readied with Tailwind, snapshot/unit tests should also be written.

### Screenshots
contact us
contact us 2 png
contact us 3

### Basic example

N/A

### Motivation

It's always good to get some feedback from users.

### PR DESCRIPTION
**Pull request by viyan-najmaldin**

### CODE REVIEW

**Review by karzan7899 — CHANGES_REQUESTED** [review]
Please update the tests

**Review by Iseluin — CHANGES_REQUESTED** [review]
It looks good but that background color, we dont use it anywhere else, so change it please.

Other than that, it does not take 100vh of the page, so that must also be fixed.

**Comment by viyan-najmaldin** [comment]
> It looks good but that background color, we dont use it anywhere else, so change it please.
> 
> Other than that, it does not take 100vh of the page, so that must also be fixed.

okey ,can you check the last request !!

**Comment by viyan-najmaldin** [comment]
> Please update the tests



> Please update the te

**Comment by viyan-najmaldin** [comment]
> 

Done

**Review by ayubabdullah — CHANGES_REQUESTED** [review]
The input fields doesn't have validation

**Comment by Iseluin** [comment]
Seconding @ayubabdullah about the validation, let's validate the fields so users cant send it empty.

**Comment by viyan-najmaldin** [comment]
> Seconding @ayubabdullah about the validation, let's validate the fields so users cant send it empty.

yes I did them, please check it now

**Comment by sarahaboudalal** [comment]
If I may add a suggestion, the contact us should be in the footer not in the navbar.

**Review by Iseluin — APPROVED** [review]
Nice job !

**Pull request merged**
