### PR TITLE
37 feature sign in sign up with facebook

### LINKED ISSUE #37: Feature : Sign In / Sign Up with Facebook
## Summary

Use Facebook authentication of Firebase to sign in the users.

Users should have a record created in the firestore database, for example in a users collection so we can save their credentials they have.

Also, when that happens, the user should also be saved in a slice (usersSlice maybe?).

### Screenshots

N/A

### Basic example

N/A

### Motivation

Adding Facebook to authentication creates good functionality diversity.

### PR DESCRIPTION
**Pull request by ayubabdullah**
add the sign in and sign up with Facebook, integrated with the button inside the components, creating redux and userSlice

### CODE REVIEW

**Review by MARWAHAKMI — APPROVED** [review]
Well Done Ayub 👍

**Review by sarahaboudalal — APPROVED** [review]
LGTM Ayub, well done!

**Review by OussamaMasri — APPROVED** [review]
Great Job Ayub!

**Review by Iseluin — CHANGES_REQUESTED** [review]
Beautifully done @ayubabdullah , there are 2 points I want to point out:

1- Oussama did the authentication with "reducers" but you used "extraReducers". Both makes sense, but this can create problems since you will be using the same slice and same initialState. We have already merged Oussama's PR, so I think you guys need to meet (as soon as possible please) and find a middle ground, maybe by changing what Oussama did with extraReducers or another way. Please pull the development, meet and talk about it to solve the problem.

2- Also, in Oussama's code, there is a function in the app.jsx which listens to the changes in the AuthState to log users in, or log users out. We need that function so please check it and also implement it in your code.

3- When I try to log in, it gives me "app not active" error. AFAIR, this is because the facebook thingy we are using there is not live. You can solve this by going to your developer settings in "facebook for developers", please follow this [link](https://stackoverflow.com/questions/73193526/app-not-active-this-app-is-not-currently-accessible-and-the-app-developer-is-aw).

Whatever you guys do with Oussama, you can directly do it in this branch(even if you will be changing Oussama's part of code, so no need for a new branch.)

**Comment by ayubabdullah** [comment]
> Beautifully done @ayubabdullah , there are 2 points I want to point out:
> 
> 1- Oussama did the authentication with "reducers" but you used "extraReducers". Both makes sense, but this can create problems since you will be using the same slice and same initialState. We have already merged Oussama's PR, so I think you guys need to meet (as soon as possible please) and find a middle ground, maybe by changing what Oussama did with extraReducers or another way. Please pull the development, meet and talk about it to solve the problem.
> 
> 2- Also, in Oussama's code, there is a function in the app.jsx which listens to the changes in the AuthState to log users in, or log users out. We need that function so please check it and also implement it in your code.
> 
> 3- When I try to log in, it gives me "app not active" error. AFAIR, this is because the facebook thingy we are using there is not live. You can solve this by going to your developer settings in "facebook for developers", please follow this [link](https://stackoverflow.com/questions/73193526/app-not-active-this-app-is-not-currently-accessible-and-the-app-developer-is-aw).
> 
> Whatever you guys do with Oussama, you can directly do it in this branch(even if you will be changing Oussama's part of code, so no need for a new branch.)

1- i did the research and found that using extraReducers and handle operation inside the slice is better practice that's why I have done it in this way, we will figure out together

Ok I'll do it

**Comment by Iseluin** [comment]
> 

It is definitely a better practice. You did it right. We need consistency therefore please adjust what Oussama did with extraReducers or the other way around.

**Review by Iseluin — APPROVED** [review]
Gorgeous !

**Pull request merged**
