### PR TITLE
72 fix fix navbar menu issue

### LINKED ISSUE #72: Fix: Fix Navbar Menu Issue
## Summary

Make the menu auto-close when you jump into a new page

### Screenshots
N/A

### Basic example

N/A

### Motivation

It's conventional :)

### PR DESCRIPTION
**Pull request by dania-diar**

### CODE REVIEW

**Review by OussamaMasri — CHANGES_REQUESTED** [review]
Great Job Dania!
Just update the Snapshot test so you can pass the CI test on GitHub

**Review by sarahaboudalal — COMMENTED** [review]
Amazing Dania, but as Oussama said, just update the snapshot and you're good to go. Good job!

**Review by OussamaMasri — APPROVED** [review]
Great Work Dania!
its working perfectly now

**Review by sarahaboudalal — APPROVED** [review]
Working perfectly, good job Dania!

**Review by ayubabdullah — APPROVED** [review]
good work dania

**Review by Iseluin — APPROVED** [review]
Great job, impressive solution, thanks @dania-diar

**Pull request merged**
