### PR TITLE
14 putting it all together create homepage

### LINKED ISSUE #14: Putting It All Together : Create Homepage
## Summary

After the components that will be inside the homepage is created, developers who put the components together should assign themselves to this issue to bring the components together in the homepage.

Styling consistency and responsiveness consistency should be tested and tweaked to have unified styling and responsiveness.

Design and responsiveness must be readied with Tailwind, snapshot/unit tests should also be written.

### Screenshots

N/A

### Basic example

N/A

### Motivation

To have a gorgeous homepage.

### PR DESCRIPTION
**Pull request by OmarBassatni97**

### CODE REVIEW

**Review by sarahaboudalal — APPROVED** [review]
Great work!

**Comment by MARWAHAKMI** [comment]
There are unwanted border-radius in both "DiffSection" and "NewsLetter" must be removed

**Review by ayubabdullah — APPROVED** [review]
Well done, great work

**Review by Iseluin — CHANGES_REQUESTED** [review]
This is not a full review, this had just struck my eye.

Newsletter should be down below.
Features Component's bg must be changed to our whitish color.
Maybe snapping feature might be added ?
Let's make the proof section (100vh - whatever navbars height is) (dont know if this would be useful if we make the navbar transparent )

**Comment by Iseluin** [comment]
> There are unwanted border-radius in both "DiffSection" and "NewsLetter" must be removed

@sarahaboudalal @OmarBassatni97 I agree with this.

**Comment by OmarBassatni97** [comment]
> This is not a full review, this had just struck my eye.
> 
> Newsletter should be down below. Features Component's bg must be changed to our whitish color. Maybe snapping feature might be added ? Let's make the proof section (100vh - whatever navbars height is) (dont know if this would be useful if we make the navbar transparent )

What is snapping feature?

**Comment by Iseluin** [comment]
> > This is not a full review, this had just struck my eye.
> > Newsletter should be down below. Features Component's bg must be changed to our whitish color. Maybe snapping feature might be added ? Let's make the proof section (100vh - whatever navbars height is) (dont know if this would be useful if we make the navbar transparent )
> 
> What is snapping feature?

When you scroll, it will snap to that section. For further reference go to lovethyneighbor.netlify.app and scroll on the homepage.

**Comment by OmarBassatni97** [comment]
> 

If we want to add this then each section must be 100vh

**Comment by Iseluin** [comment]
> > 
> 
> If we want to add this then each section must be 100vh

not really, we can make 2 sections into 1/2 vh and snap to the first one, so 2 sections in 100vh

**Review by OussamaMasri — APPROVED** [review]
Great Job Omar!

**Review by Iseluin — CHANGES_REQUESTED** [review]
I suppose the diffSection (video) and features component needs to swap places.

**Review by Iseluin — APPROVED** [review]
Approving this for now to create a better folder structure. There are some design concerns that we might deal with later.

**Pull request merged**
