### PR TITLE
83 fix background color of the navbar

### LINKED ISSUE #83: Fix: Background Color of the NavBar
make the background color of the NavBar transparent and add opacity to it

### PR DESCRIPTION
**Pull request by OmarBassatni97**

### CODE REVIEW

**Review by sarahaboudalal — CHANGES_REQUESTED** [review]
it looks great @OmarBassatni97 
however, it's still swallowing half of the sign-up text, can we fix that?

**Comment by OmarBassatni97** [comment]
> it looks great @OmarBassatni97 however, it's still swallowing half of the sign-up text, can we fix that?

I didn't get what you said can you explain more please

**Review by ayubabdullah — COMMENTED** [review]
the hover color has a problem, when you hover it the text become kinda invisible

**Comment by OmarBassatni97** [comment]
> the hover color has a problem, when you hover it the text become kinda invisible

your saying the color needs to be changed?

**Comment by ayubabdullah** [comment]
> > the hover color has a problem, when you hover it the text become kinda invisible
> 
> your saying the color needs to be changed?

exactly the hover color should be darker because the background is  light

**Comment by OmarBassatni97** [comment]
> > > the hover color has a problem, when you hover it the text become kinda invisible
> > 
> > 
> > your saying the color needs to be changed?
> 
> exactly the hover color should be darker because the background is light

Okay I will make it darker

**Review by sarahaboudalal — COMMENTED** [review]
did u change it back to the way it was on purpose?

**Comment by sarahaboudalal** [comment]
> did u change it back to the way it was on purpose?
Oh I see, when it is at the top the colors are the way they were in the beginning, but when i scroll down they change to the new version color

**Comment by OmarBassatni97** [comment]
> > did u change it back to the way it was on purpose?
> > Oh I see, when it is at the top the colors are the way they were in the beginning, but when i scroll down they change to the new version color

Yes this way the problem that we had in the sign up page is solved to

**Review by OussamaMasri — CHANGES_REQUESTED** [review]
most of the transition are gone now 
also for the responsiveness you can make the dropDown menu come from the right to the left instead of coming from the top and the dropdown transition is gone
because now there's a gap between the menu and the dropdown thing so instead of top-[-number px] you can make it left-[-number]

**Review by ayubabdullah — CHANGES_REQUESTED** [review]
the navbar is not responsive on mobile size

**Review by Iseluin — CHANGES_REQUESTED** [review]
Since this is a constant WIP, can we change this to a draft PR, leave it as is and work on our other current issues ?

**Review by Iseluin — APPROVED** [review]
:')

**Pull request merged**
