### PR TITLE
16 create footer

### LINKED ISSUE #16: Create : Footer
## Summary

Footer will have the social media links, links to our team, contact us and faq components. Can have a copyright paragraph.

Design and responsiveness must be readied with Tailwind, snapshot/unit tests should also be written.

### Screenshots

Footer

or

Footer 2

### Basic example

N/A

### Motivation

To store important links on the webpage and to showcase our social media links.

### PR DESCRIPTION
**Pull request by karzan7899**
Guys, The Footer is done. Please give us your feedback.

### CODE REVIEW

**Comment by sarahaboudalal** [comment]
@karzan7899 who said we're using yellow

**Comment by Iseluin** [comment]
@karzan7899 @zahraaz can you folks fix the conflicts before the reviews please ?

**Comment by ZahraaMahmood** [comment]
> @karzan7899 @zahraaz can you folks fix the conflicts before the reviews please ?

conflicts solved ✔✨

**Comment by Iseluin** [comment]
> > @karzan7899 @zahraaz can you folks fix the conflicts before the reviews please ?
> 
> conflicts solved ✔✨

But at what cost? Now the deployment is not working. Can you pull the branch and check the errors. Theres something wrong with the searchBar component

**Comment by ZahraaMahmood** [comment]
> > > @karzan7899 @zahraaz can you folks fix the conflicts before the reviews please ?
> > 
> > 
> > conflicts solved ✔✨
> 
> But at what cost? Now the deployment is not working. Can you pull the branch and check the errors. Theres something wrong with the searchBar component

I'm working on it at the moment. Is it acceptable now?

**Review by ayubabdullah — CHANGES_REQUESTED** [review]
The footer is not full width in desktop mode, and it's not responsive

**Review by MARWAHAKMI — COMMENTED** [review]
As Ayub said, it’s not responsive, and you must make it the entire screen width.
And putting links to home and profile pages isn’t the right place on the footer.
If you can use another version of the logo, not the same one on the navbar.

**Review by OmarBassatni97 — CHANGES_REQUESTED** [review]
The navbar must be full width and I vote for changing the layout because it looks like a navbar more than a footer

**Comment by karzan7899** [comment]
Thank you all for your valuable feedbacks. the navbar responsive part has been resolved. But as you guys pointed out and @zahraaz  and I realize that our footer is lacking the footer feature & distinctiveness. It looks like a navbar more. We will fix them soon

**Comment by OussamaMasri** [comment]
its not responsive and its not taking full the full width on the desktop
and it does look like the navbar so we need to make it special or noticeable that its a footer

**Review by Iseluin — CHANGES_REQUESTED** [review]
I am not against a subtle footer like this at all. But, and this is a big but:

- Home, contact, about and profile should not be there.
- You can add our team, contact us and faq there if you want.
- No need for the logo there.
- Also add some social media links with their accounts please.
- Make it responsive, and make it span the whole width of the viewport height.

As I said, I dont mind it being subtle, I even would encourage it to be subtle. I liked the Donate button too.

**Comment by OmarBassatni97** [comment]
This is so much better Karzan !

**Review by ayubabdullah — APPROVED** [review]
Good work guys, just if you can add a hover effect to links it will be much better other than that it looks great

**Review by Iseluin — CHANGES_REQUESTED** [review]
This looks nice and I am aware that it is still not finished, and we dont PR unfinished stuff, so can you people change this into a draft PR ? How you might ask, I'd say google it. And there are conflicts that needs to be resolved.

**Comment by OmarBassatni97** [comment]
I propose to delete the top margin from the footer

**Review by Iseluin — APPROVED** [review]

**Pull request merged**
