### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by sarahaboudalal**
1) Changed the navbar dropdown styling making it fit with the glassy style (kinda) by adding opacity to the bg color
2) the item cards width wasn't going right with the responsiveness, fixed 
3) also there was something wrong with the height of the user's item cards, now it's fixed
4) in the about us page some images weren't showing, also fixed :D

### CODE REVIEW

**Comment by OmarBassatni97** [comment]
where can I see the changes @sarahaboudalal ?

**Comment by sarahaboudalal** [comment]
> where can I see the changes @sarahaboudalal ?

ohhh the deployment isn't working anymore, i guess u need to pull, checkout to `navbar` branch, and yarn start

**Review by OmarBassatni97 — APPROVED** [review]
Nice changes Sarah! Good Job

**Review by OussamaMasri — APPROVED** [review]
Great job Sarah!

**Pull request merged**
