### PR TITLE
created folder for custom-button and search-bar

### LINKED ISSUE #73: Fix : Fix Folder Structure of SearchBar and Custom Button
## Description

They are not inside their own folders. Move them to their home please.

## Steps to Reproduce

1. Move them in their warm fuzzy folders so they wont get cold in this cold winter.

### PR DESCRIPTION
**Pull request by OmarBassatni97**

### CODE REVIEW

**Review by Iseluin — CHANGES_REQUESTED** [review]
Start with Capital letter and use camelcase for the customcomponents folder please.

**Comment by OmarBassatni97** [comment]
What is going on here?
I synced with the dev branch and this happened

**Comment by Iseluin** [comment]
> What is going on here? I synced with the dev branch and this happened

Seems like you forgot to rename the **folder** to CustomComponents, its still all lowercase. I think thats why CI is failing.

**Review by Iseluin — APPROVED** [review]
👍🏻

**Pull request merged**
